### PR TITLE
Implement new interface and priority based fading logic

### PR DESCRIPTION
**Pull request by Aelexe**
**IMPORTANT**: Backup your config prior to testing this. It uses a new config structure and overwrites the existing one.

I've implemented a new config UI to address the inevitable bloat of the matrix as more elements and states were added. I've also added the ability to reorder state priority to allow for more flexibility.

Idle transition delay and my other recent changes are still to be completed.

fader-plugin

### CODE REVIEW

**Comment by shdwp** [comment]
Looks great! 

Do you wanna a maintainer role in the project by the way? Fader has unfortunately been an orphan for a few months due to my IRL problems. I can give you access to the repo and also drop a word to goaats so that you can submit builds to the repo.

**Comment by Aelexe** [comment]
Sure thing. I'd be happy to help look after it.

**Comment by Aelexe** [comment]
All features have been merged across so this should be safe to merge now.

**Comment by shdwp** [comment]
I've send you an invite for the repo. If you accept it you can merge it yourself. I will also drop a message to the dalamud team so they will know that they can accept updates from you and not me.

**Pull request merged**
